onlyBuiltDependencies:
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - workerd

overrides:
  ajv@<8.18.0: '>=8.18.0'
  esbuild@<=0.24.2: '>=0.25.0'
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  hono@<4.11.4: '>=4.11.4'
  hono@<4.11.7: '>=4.11.7'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
